# Generated by Django 5.2a1 on 2025-05-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_uploadedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
