# Generated by Django 5.1.5 on 2025-06-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_followrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(blank=True, to="core.userprofile"),
        ),
    ]
