# Generated by Django 5.1.5 on 2025-06-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_userprofile_friends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followrequest",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("accepted", "Accepted")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
