# Generated by Django 5.1.5 on 2025-07-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_followrequest_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="followrequest",
            name="status",
        ),
        migrations.AddField(
            model_name="followrequest",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
