# Generated by Django 5.1.5 on 2025-07-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_followrequest_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
